defaults:
  - adapters@adapter: lora
  - _self_
initialization:
  path: ${runtime.base_dir}/models/hub/models--Qwen--Qwen2.5-Math-1.5B/snapshots/4a83ca6e4526a4f2da3aa259ec36c259f66b2ab2
  adapter: null
  tokenizer: null
dtype: float16
attention: sdpa
gradient_checkpointing: true
